"""Model-layer schema — LLMRequest, LLMResponse, ModelConfig, RouterConfig."""

from typing import Any

from pydantic import BaseModel, Field

from evoagent.core.message import Message, ToolCall


class LLMRequest(BaseModel):
    """A request to an LLM provider.

    This is the model-layer version with full provider control
    (stream, tool_choice, response_format) beyond the core
    abstract version.
    """

    messages: list[Message] = Field(
        default_factory=list,
        description="Messages to send to the LLM.",
    )
    model: str | None = Field(
        default=None,
        description="Model name override. If None, use provider default.",
    )
    temperature: float = Field(default=0.0, description="Sampling temperature.")
    max_tokens: int | None = Field(
        default=4096,
        description="Max tokens in response.",
    )
    tools: list[dict[str, Any]] | None = Field(
        default=None,
        description="Function-calling tool schemas.",
    )
    tool_choice: str | dict[str, Any] | None = Field(
        default=None,
        description="Tool choice constraint: 'auto', 'none', 'required', or specific.",
    )
    response_format: dict[str, Any] | None = Field(
        default=None,
        description="Response format constraint, e.g. {'type': 'json_object'}.",
    )
    stream: bool = Field(default=False, description="Whether to stream the response.")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extra metadata.",
    )


class LLMResponse(BaseModel):
    """A response from an LLM provider.

    This is the model-layer version with raw response and
    provider identification.
    """

    content: str = Field(default="", description="Text content from the LLM.")
    model: str = Field(default="", description="Model that produced this response.")
    provider: str = Field(default="", description="Provider name (deepseek, openai, etc.).")
    tool_calls: list[ToolCall] | None = Field(
        default=None,
        description="Tool calls generated by the LLM.",
    )
    raw: dict[str, Any] = Field(
        default_factory=dict,
        description="Raw provider response for debugging.",
    )
    usage: dict[str, Any] = Field(
        default_factory=dict,
        description="Token usage: {prompt_tokens, completion_tokens, total_tokens}.",
    )
    finish_reason: str | None = Field(
        default=None,
        description="Why the LLM stopped: stop, tool_calls, length, content_filter.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extra metadata.",
    )


class ModelConfig(BaseModel):
    """Configuration for a single model provider instance."""

    provider: str = Field(default="deepseek", description="Provider name.")
    model: str = Field(default="deepseek-chat", description="Model name.")
    base_url: str = Field(
        default="https://api.deepseek.com/v1",
        description="API base URL.",
    )
    api_key_env: str = Field(
        default="DEEPSEEK_API_KEY",
        description="Environment variable name for the API key.",
    )
    temperature: float = Field(default=0.0, description="Default sampling temperature.")
    max_tokens: int = Field(default=4096, description="Default max tokens.")
    timeout: int = Field(default=60, description="Request timeout in seconds.")
    max_retries: int = Field(default=3, description="Max retry attempts on failure.")


class RouterConfig(BaseModel):
    """Configuration mapping roles to model configs."""

    planner: ModelConfig = Field(
        default_factory=lambda: ModelConfig(model="deepseek-reasoner"),
        description="Model for planning tasks.",
    )
    executor: ModelConfig = Field(
        default_factory=ModelConfig,
        description="Model for task execution.",
    )
    critic: ModelConfig = Field(
        default_factory=lambda: ModelConfig(model="deepseek-reasoner"),
        description="Model for critique/reflection.",
    )
    summarizer: ModelConfig = Field(
        default_factory=ModelConfig,
        description="Model for summarization.",
    )
    default: ModelConfig = Field(
        default_factory=ModelConfig,
        description="Fallback model for any role.",
    )
