"""Message and ContentBlock types."""

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

from evoagent.core.ids import generate_id
from evoagent.core.time import utc_now_iso


class MessageRole(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ContentBlockType(StrEnum):
    TEXT = "text"
    JSON = "json"
    CODE = "code"
    ERROR = "error"


class ContentBlock(BaseModel):
    """A typed content block within a message.

    Supports text, JSON, code, and error content types
    for richer message representation.
    """

    type: ContentBlockType = Field(
        default=ContentBlockType.TEXT,
        description="Content type: text, json, code, or error.",
    )
    content: str = Field(default="", description="The content payload.")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extra metadata (language, filename, etc.).",
    )


class ToolCall(BaseModel):
    """A tool call generated by an LLM assistant message."""

    id: str = Field(
        default_factory=lambda: generate_id("call"),
        description="Unique tool call ID.",
    )
    name: str = Field(..., description="Tool name.")
    arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Tool arguments as key-value pairs.",
    )
    raw: str = Field(
        default="",
        description="Raw JSON string from the LLM before parsing.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extra metadata (model, token usage, etc.).",
    )


class Message(BaseModel):
    """A chat message in the agent conversation history.

    Supports system, user, assistant, and tool roles.
    Assistant messages may carry tool_calls; tool messages
    reference a tool_call_id.
    """

    role: MessageRole = Field(..., description="Message role.")
    content: str = Field(default="", description="Message text content.")
    name: str | None = Field(
        default=None,
        description="Optional sender name.",
    )
    tool_call_id: str | None = Field(
        default=None,
        description="For tool messages: the ID of the tool call this responds to.",
    )
    tool_calls: list[ToolCall] | None = Field(
        default=None,
        description="For assistant messages: tool calls generated by the LLM.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extra metadata (token count, model, etc.).",
    )
    created_at: str = Field(
        default_factory=utc_now_iso,
        description="ISO-8601 creation timestamp.",
    )
